name: lint-build-deploy

on:
  push:
    branches:
      - main

jobs:
  build_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install all dependencies
        run: yarn install --frozen-lockfile
      - name: Run linting
        run: yarn lint

  build_and_deploy:
    needs: build_and_lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install all dependencies
        run: yarn install --frozen-lockfile
      - name: Run build
        run: yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_VISUALISATOR }}"
          channelId: live
          projectId: visualisator
